// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC61uOOK-kmotuQKTsCKIrkjDAYAQ5CYAw',
    appId: '1:804643911321:web:04eb7a4fd597ee5b216a08',
    messagingSenderId: '804643911321',
    projectId: 'homes-6b1dd',
    authDomain: 'homes-6b1dd.firebaseapp.com',
    databaseURL: 'https://homes-6b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'homes-6b1dd.firebasestorage.app',
    measurementId: 'G-Y17QKEDKV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeg3HFKw_oo2UoW3TNubDO1bn7mfRFH6c',
    appId: '1:804643911321:android:1576a4f96a0f87f1216a08',
    messagingSenderId: '804643911321',
    projectId: 'homes-6b1dd',
    databaseURL: 'https://homes-6b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'homes-6b1dd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC61uOOK-kmotuQKTsCKIrkjDAYAQ5CYAw',
    appId: '1:804643911321:web:c2af925e8626bdf8216a08',
    messagingSenderId: '804643911321',
    projectId: 'homes-6b1dd',
    authDomain: 'homes-6b1dd.firebaseapp.com',
    databaseURL: 'https://homes-6b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'homes-6b1dd.firebasestorage.app',
    measurementId: 'G-LN2LPRQNV2',
  );

}